name: Discord Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir çalışacak (isteğe bağlı)

jobs:
  update-discord:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Discord update script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python update_roles.py
